# Use the official Node.js image as the base image for building
FROM node:14 as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code to the working directory
COPY . .

# Build the React app
RUN npm run build

# Use a lightweight web server as the base image for serving the app
FROM nginx:alpine

# Copy the built app to the web server's root directory
COPY --from=build /app/build /usr/share/nginx/html
